### ISSUE TITLE
legoとcodeの値受け渡し方法

### ISSUE THREAD

**Issue by ring18** [ring18/candy-and-stick#1]
必要なapplication？
ラズパイで可能か？

**Comment by YS11-1600** [comment]
ラズパイとMIndstormsの接続
https://bitterharvest.hatenablog.com/entry/2015/06/28/115546

**Comment by yattinda** [comment]
https://qiita.com/taguchi-n2310/items/3ee7de6dd4ed8ba52c54
RaspiとEV3でシリアル通信ができそう

**Comment by ring18** [comment]
ラズパイ詰んだマインドストーム
https://www.souichi.club/lego/ev3-auto-ml-01/

**Comment by yattinda** [comment]
LGTM
