### ISSUE TITLE
クラス図の改修

### ISSUE THREAD

**Issue by yattinda** [ring18/candy-and-stick#13]

**Comment by ring18** [comment]
[candyStick-class (1).pdf](https://github.com/ring18/candy-and-stick/files/14136871/candyStick-class.1.pdf)

推定とデータ処理二つをまとめた
画像カウント用関数recordDataとカウント用変数追加
レゴとの連携を追加
クラス名変更

**Comment by ring18** [comment]
![candyStick-class](https://github.com/ring18/candy-and-stick/assets/58505661/6c6fe329-3a5e-4ea9-81f7-5fe3a8b982cb)

**Comment by yattinda** [comment]
LGTM
