### ISSUE TITLE
疲労（集中）度判定

### ISSUE THREAD

**Issue by YS11-1600** [ring18/candy-and-stick#2]
使う技術と大まかな流れに関する調査

**Comment by yattinda** [comment]
https://learnopencv.com/head-pose-estimation-using-opencv-and-dlib/
頭部方向推定

**Comment by YS11-1600** [comment]
web カメラを用いた瞬き検出による集中度評価（論文）
https://ipsj.ixsq.nii.ac.jp/ej/?action=repository_action_common_download&item_id=165252&item_no=1&attribute_id=1&file_no=1

**Comment by YS11-1600** [comment]
頭部姿勢推定の実装（ゆるふわ）
https://zenn.dev/ykesamaru/articles/025b0eabf24e20

**Comment by yattinda** [comment]
LGTM
