### ISSUE TITLE
raspiからのレゴ動作実現

### ISSUE THREAD

**Issue by ring18** [ring18/candy-and-stick#28]

**Comment by yattinda** [comment]
bluetooth接続はプロトコルのエラーで失敗（おそらく規格が古すぎ）

**Comment by yattinda** [comment]
有線接続で接続可能（動作未確認）

**Comment by yattinda** [comment]
接続確認
有線接続でBeep音を確認
参照元
https://qiita.com/masterkeaton12/items/938457911b0f3f25e161

**Comment by yattinda** [comment]
https://www.naruto-u.ac.jp/facultystaff/ito/research-paper-public/2020/python-ev3-textbook.pdf

**Comment by yattinda** [comment]
https://qiita.com/saba383810/items/be7227e88d25b17e6906

**Comment by yattinda** [comment]
https://github.com/ev3dev/brickrun?tab=readme-ov-file

**Comment by yattinda** [comment]
SSH接続で解決
