### ISSUE TITLE
起動フェーズ

### ISSUE THREAD

**Issue by ring18** [ring18/candy-and-stick#3]

**Comment by yattinda** [comment]
/png/RLB1JiCm3BtdAwoTOH-m0ngRGEA2q0RdAKszDIA9fzXbzBP_vKT8qgqP4fVKURRVir-wPD5HUk-KDa8HFXYZQgWFhOu3p5P40Zome9-1PcZINHaA4id1xEbRUnkqM0f0UrYJztsmfW2bt93V2N9j6GcVjK68QEWGx5IxJ-2ky5VvhUZGDaF9ynZVPDSKc1p2raJ4aGHZfAXKtWBk7yPnyv4lTPWnA61LdQ84JsArD84ZUQshM3bpNx5F1HBCqxogbMPhTclgey65Uk-mL41fryvTh9sNp4RpiKbC0xnPC1sQJp2tZiB9IWVIuS_vlA66fBG5-DlO_6VmfFEoBxB7I0QPaU50S4Bdxi3J5uBGTVFy5PmhzUW4OtxZbCvxC2uA2nYCecsuSa5Bo118AcLh-UZq03gCDW65F3wOoxib8OXOVi0ozbnXGh9vQfcYthjV

**Comment by yattinda** [comment]
暫定版完成
![morikawa_boot](https://github.com/ring18/candy-and-stick/assets/50829936/c8dab0fb-5739-445d-98d0-87402197bcd2)
